import { z } from "zod";

export const IpInfoSchema = z.object({
  ip: z.string().ip(),
  network: z.string().optional().catch(""),
  version: z.string().optional().catch(""),
  city: z.string().optional().catch(""),
  region: z.string().optional().catch(""),
  region_code: z.string().optional().catch(""),
  country: z.string().optional().catch(""),
  country_name: z.string().optional().catch(""),
  country_code: z.string().optional().catch(""),
  country_code_iso3: z.string().optional().catch(""),
  country_capital: z.string().optional().catch(""),
  country_tld: z.string().optional().catch(""),
  continent_code: z.string().optional().catch(""),
  in_eu: z.boolean().optional().catch(false),
  postal: z.string().optional().catch(""),
  latitude: z.number().optional().nullish(),
  longitude: z.number().optional().nullish(),
  timezone: z.string().optional().catch(""),
  utc_offset: z.string().optional().catch(""),
  country_calling_code: z.string().optional().catch(""),
  currency: z.string().optional().catch(""),
  currency_name: z.string().optional().catch(""),
  languages: z.string().optional().catch(""),
  country_area: z.number().optional().nullish(),
  country_population: z.number().optional().nullish(),
  asn: z.string().optional().catch(""),
  org: z.string().optional().catch(""),
});
